name: torri
description: "The mobile app for Torri"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  webview_flutter: ^4.10.0
  get_it: ^8.0.3
  http_parser: ^4.1.1
  provider: ^6.1.2
  animated_tree_view: ^2.3.0
  intl: ^0.20.1
  loading_animation_widget: ^1.3.0
  shared_preferences: ^2.3.5
  flag: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_foreground: "assets/icon.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
